[package]
name = "paw"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.9.0"
indicatif = "0.16.2"
console = "0.15.0"
aws-config = "0.6.0"
aws-sdk-sfn = "0.6.0"
aws-smithy-types = "0.36.0"
tokio = { version = "1", features = ["full"] }